<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-16 at 14:19:45.
 */
class FantasticoTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Fantastico
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Fantastico;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\Fantastico\Fantastico::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::get_ip_types
     * @todo   Implement testGet_ip_types().
     */
    public function testGet_ip_types()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::is_type
     * @todo   Implement testIs_type().
     */
    public function testIs_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::getIpList
     * @todo   Implement testGetIpList().
     */
    public function testGetIpList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::getIpListDetailed
     * @todo   Implement testGetIpListDetailed().
     */
    public function testGetIpListDetailed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::valid_ip
     * @todo   Implement testValid_ip().
     */
    public function testValid_ip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::getIpDetails
     * @todo   Implement testGetIpDetails().
     */
    public function testGetIpDetails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::editIp
     * @todo   Implement testEditIp().
     */
    public function testEditIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::addIp
     * @todo   Implement testAddIp().
     */
    public function testAddIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::deactivateIp
     * @todo   Implement testDeactivateIp().
     */
    public function testDeactivateIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::reactivateIp
     * @todo   Implement testReactivateIp().
     */
    public function testReactivateIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\Fantastico\Fantastico::deleteIp
     * @todo   Implement testDeleteIp().
     */
    public function testDeleteIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
